import mongoose from "mongoose";

const usertransporterrelationshipSchema = new mongoose.Schema(
  {
    companyName: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    prices: [
      {
        transporterid: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Transporter",
        },
        priceRate: {
          minWeight: {
            type: Number,
            required: true,
            default: 0,
          },
          docketCharges: {
            type: Number,
            required: true,
            default: 0,
          },
          fuel: {
            type: Number,
            required: true,
            default: 0,
          },
          rovCharges: {
            variable: {
              type: Number,
              required: true,
              default: 0,
            },
            fixed: {
              type: Number,
              required: true,
              default: 0,
            },
          },
          inuaranceCharges: {
            variable: {
              type: Number,
              required: true,
              default: 0,
            },
            fixed: {
              type: Number,
              required: true,
              default: 0,
            },
          },
          odaCharges: {
            variable: {
              type: Number,
              required: true,
              default: 0,
            },
            fixed: {
              type: Number,
              required: true,
              default: 0,
            },
          },
          codCharges: {
            variable: {
              type: Number,
              required: true,
              default: 0,
            },
            fixed: {
              type: Number,
              required: true,
              default: 0,
            },
          },
          prepaidCharges: {
            variable: {
              type: Number,
              required: true,
              default: 0,
            },
            fixed: {
              type: Number,
              required: true,
              default: 0,
            },
          },
          topayCharges: {
            variable: {
              type: Number,
              required: true,
              default: 0,
            },
            fixed: {
              type: Number,
              required: true,
              default: 0,
            },
          },
          handlingCharges: {
            variable: {
              type: Number,
              required: true,
              default: 0,
            },
            fixed: {
              type: Number,
              required: true,
              default: 0,
            },
          },
          fmCharges: {
            variable: {
              type: Number,
              required: true,
              default: 0,
            },
            fixed: {
              type: Number,
              required: true,
              default: 0,
            },
          },
          appointmentCharges: {
            variable: {
              type: Number,
              required: true,
              default: 0,
            },
            fixed: {
              type: Number,
              required: true,
              default: 0,
            },
          },
          divisor: {
            type: Number,
            required: true,
            default: 1,
          },
          minCharges: {
            type: Number,
            required: true,
            default: 0,
          },
          greenTax: {
            type: Number,
            required: true,
            default: 0,
          },
          daccCharges: {
            type: Number,
            required: true,
            default: 0,
          },
          miscellanousCharges: {
            type: Number,
            required: true,
            default: 0,
          },
        },
      },
    ],
    priceChart: {
      N1: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      N2: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      N3: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      W1: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      W2: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      S1: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      S2: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      S3: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      E1: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      E2: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      C1: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      C2: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      NE1: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
      NE2: {
        N1: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N2: { type: Number, default: 0 },
        N3: { type: Number, default: 0 },
        W1: { type: Number, default: 0 },
        W2: { type: Number, default: 0 },
        S1: { type: Number, default: 0 },
        S2: { type: Number, default: 0 },
        S3: { type: Number, default: 0 },
        E1: { type: Number, default: 0 },
        E2: { type: Number, default: 0 },
        C1: { type: Number, default: 0 },
        C2: { type: Number, default: 0 },
        NE1: { type: Number, default: 0 },
        NE2: { type: Number, default: 0 },
      },
    },
  },
  { timestamps: true }
);

export default mongoose.model(
  "usertransporterrelationship",
  usertransporterrelationshipSchema
);
